"""
Модуль содержит библиотеку навыков, их рецепты, множители опыта и логику прогрессии.

Определяет, как навыки связаны с характеристиками персонажа,
какие множители опыта применяются, а также пороги для получения
различных званий в каждом навыке.
"""

BASE_MAX_XP = 1_000_000

SKILL_RECIPES = {
    "melee_combat": {
        "stat_weights": {"strength": 2.0, "agility": 1.0},
        "title_ru": "Ближний бой",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "ranged_combat": {
        "stat_weights": {"agility": 2.0, "perception": 1.0},
        "title_ru": "Дальний бой",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "light_armor": {
        "stat_weights": {"endurance": 2.0, "agility": 1.0},
        "title_ru": "Легкая броня",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "medium_armor": {
        "stat_weights": {"endurance": 2.0, "strength": 1.0},
        "title_ru": "Средняя броня",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "heavy_armor": {
        "stat_weights": {"strength": 2.0, "endurance": 1.0},
        "title_ru": "Тяжелая броня",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "shield": {
        "stat_weights": {"strength": 2.0, "agility": 1.0},
        "title_ru": "Щит",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "intuition": {
        "stat_weights": {"agility": 2.0, "wisdom": 1.0},
        "title_ru": "Интуиция",
        "xp_multiplier": 0.8,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "reflexes": {
        "stat_weights": {"wisdom": 2.0, "agility": 1.0},
        "title_ru": "Рефлексы",
        "xp_multiplier": 0.8,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "fortitude": {
        "stat_weights": {"endurance": 2.0, "men": 1.0},
        "title_ru": "Стойкость",
        "xp_multiplier": 0.8,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "persistence": {
        "stat_weights": {"strength": 2.0, "intelligence": 1.0},
        "title_ru": "Настойчивость",
        "xp_multiplier": 0.8,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "mining": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Горное дело",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "herbalism": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Травничество",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "skinning": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Снятие шкур",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "woodcutting": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Лесорубство",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "hunting": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Охота",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "archaeology": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Археология",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "gathering": {
        "stat_weights": {"perception": 2.0, "endurance": 1.0},
        "title_ru": "Сбор",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "alchemy": {
        "stat_weights": {"intelligence": 2.0, "agility": 1.0},
        "title_ru": "Алхимия",
        "xp_multiplier": 1.5,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "science": {
        "stat_weights": {"intelligence": 2.0, "perception": 1.0},
        "title_ru": "Наука",
        "xp_multiplier": 1.5,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "weapon_craft": {
        "stat_weights": {"intelligence": 2.0, "agility": 1.0},
        "title_ru": "Оружейное дело",
        "xp_multiplier": 2.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "armor_craft": {
        "stat_weights": {"intelligence": 2.0, "agility": 1.0},
        "title_ru": "Бронное дело",
        "xp_multiplier": 2.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "jewelry_craft": {
        "stat_weights": {"intelligence": 2.0, "agility": 1.0},
        "title_ru": "Ювелирное дело",
        "xp_multiplier": 2.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "artifact_craft": {
        "stat_weights": {"intelligence": 2.0, "agility": 1.0},
        "title_ru": "Создание артефактов",
        "xp_multiplier": 2.5,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "accounting": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Бухгалтерия",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "brokerage": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Посредничество",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "contracts": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Договоры",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "trade_relations": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Торговые связи",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "leadership": {
        "stat_weights": {"charisma": 2.0, "luck": 1.0},
        "title_ru": "Лидерство",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "organization": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Организация",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "team_spirit": {
        "stat_weights": {"charisma": 2.0, "luck": 1.0},
        "title_ru": "Командный дух",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "egoism": {
        "stat_weights": {"luck": 2.0, "charisma": 1.0},
        "title_ru": "Эгоизм",
        "xp_multiplier": 1.0,
        "prerequisite_skill": None,
        "prerequisite_title": None,
    },
    "advanced_melee_combat": {
        "stat_weights": {"strength": 2.0, "agility": 1.0},
        "title_ru": "Продвинутый ближний бой",
        "xp_multiplier": 5.0,
        "prerequisite_skill": "melee_combat",
        "prerequisite_title": "⚜️ Грандмастер",
    },
    "advanced_ranged_combat": {
        "stat_weights": {"agility": 2.0, "perception": 1.0},
        "title_ru": "Продвинутый дальний бой",
        "xp_multiplier": 5.0,
        "prerequisite_skill": "ranged_combat",
        "prerequisite_title": "⚜️ Грандмастер",
    },
}

TITLE_THRESHOLDS_PERCENT = {
    100: "🔱 Абсолют",
    75: "⚜️ Гранд-мастер",
    45: "⭐ Мастер",
    25: "🏆 Адепт",
    10: "📗 Продвинутый",
    0: "🌱 Новичок",
}
