"""
СЕМЕЙСТВО: АБЕРРАЦИИ / ПУСТОТА (Психика, искажение, безумие)
============================================================
Логика: искажение -> безумие -> поглощение
"""

from ..monster_structs import MonsterFamily

ABERRATIONS_FAMILY: MonsterFamily = {
    "id": "void_spawn",
    "archetype": "demon",
    "organization_type": "solitary",
    "default_tags": ["aberration", "void", "eldritch", "psychic"],
    "hierarchy": {
        "minions": ["void_leech", "gazer", "flesh_crawler"],
        "veterans": ["tentacle_beast", "mind_flayer_initiate", "shifter"],
        "elites": ["shambling_horror", "void_walker", "reality_warper"],
        "boss": ["elder_brain", "cosmic_horror", "gate_of_madness"],
    },
    "variants": {
        # --- 1. Мелкие ужасы (Minions) [Tier 4-7] ---
        "void_leech": {
            "id": "void_leech",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating, slug-like creature that drains mental energy.",
            "extra_tags": ["leech", "psychic"],
            "base_stats": {
                "strength": 4,
                "agility": 8,
                "endurance": 6,
                "intelligence": 8,
                "wisdom": 6,
                "men": 15,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "debuff_weaken"],
        },
        "gazer": {
            "id": "gazer",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating eyeball held aloft by smaller, twitching eyes. Its gaze causes confusion.",
            "extra_tags": ["gazer", "beholderkin"],
            "base_stats": {
                "strength": 2,
                "agility": 10,
                "endurance": 5,
                "intelligence": 10,
                "wisdom": 8,
                "men": 12,
                "perception": 16,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "debuff_stun"],
        },
        "flesh_crawler": {
            "id": "flesh_crawler",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A mass of flesh and limbs that drags itself across the ground.",
            "extra_tags": ["flesh", "amorphous"],
            "base_stats": {
                "strength": 10,
                "agility": 6,
                "endurance": 10,
                "intelligence": 1,
                "wisdom": 1,
                "men": 8,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_slow"],
        },
        # --- 2. Опытные кошмары (Veterans) [Tier 4-7] ---
        "tentacle_beast": {
            "id": "tentacle_beast",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A creature composed of writhing tentacles. It grabs and crushes.",
            "extra_tags": ["tentacles", "grappler"],
            "base_stats": {
                "strength": 14,
                "agility": 10,
                "endurance": 12,
                "intelligence": 4,
                "wisdom": 4,
                "men": 10,
                "perception": 12,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_stun"],
        },
        "mind_flayer_initiate": {
            "id": "mind_flayer_initiate",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A humanoid figure with facial tentacles, learning to blast minds.",
            "extra_tags": ["mind_flayer", "psychic"],
            "base_stats": {
                "strength": 8,
                "agility": 8,
                "endurance": 8,
                "intelligence": 14,
                "wisdom": 12,
                "men": 20,
                "perception": 14,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_ranged"],
        },
        "shifter": {
            "id": "shifter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A creature that constantly changes its shape, making it hard to hit.",
            "extra_tags": ["shapeshifter", "unstable"],
            "base_stats": {
                "strength": 10,
                "agility": 14,
                "endurance": 10,
                "intelligence": 6,
                "wisdom": 6,
                "men": 15,
                "perception": 12,
                "charisma": 1,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "special_unique"],
        },
        # --- 3. Элита (Elites) [Tier 5-7] ---
        "shambling_horror": {
            "id": "shambling_horror",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A large, amorphous blob of eyes, mouths, and limbs. Its presence inspires madness.",
            "extra_tags": ["amorphous", "terror"],
            "base_stats": {
                "strength": 18,
                "agility": 6,
                "endurance": 22,
                "intelligence": 8,
                "wisdom": 8,
                "men": 25,
                "perception": 16,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_weaken", "debuff_weaken"],
        },
        "void_walker": {
            "id": "void_walker",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A humanoid silhouette made of pure darkness, seemingly absorbing light.",
            "extra_tags": ["void", "shadow", "teleport"],
            "base_stats": {
                "strength": 14,
                "agility": 16,
                "endurance": 14,
                "intelligence": 10,
                "wisdom": 10,
                "men": 20,
                "perception": 14,
                "charisma": 1,
                "luck": 8,
            },
            "fixed_loadout": {},
            "skills": ["stealth", "attack_heavy", "debuff_blind"],
        },
        "reality_warper": {
            "id": "reality_warper",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A creature that bends space around it, causing attacks to miss.",
            "extra_tags": ["magic", "reality_bender"],
            "base_stats": {
                "strength": 10,
                "agility": 12,
                "endurance": 16,
                "intelligence": 16,
                "wisdom": 14,
                "men": 30,
                "perception": 18,
                "charisma": 1,
                "luck": 15,
            },
            "fixed_loadout": {},
            "skills": ["buff_reflect", "special_unique", "debuff_slow"],
        },
        # --- 4. Неописуемое (Bosses) [Tier 6-7] ---
        "elder_brain": {
            "id": "elder_brain",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A massive, pulsating brain in a vat of fluid. It commands all lesser creatures with its mind.",
            "extra_tags": ["leader", "psychic", "stationary"],
            "base_stats": {
                "strength": 5,
                "agility": 0,
                "endurance": 40,
                "intelligence": 40,
                "wisdom": 30,
                "men": 80,
                "perception": 30,
                "charisma": 10,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_stun", "summon_minion", "debuff_weaken"],
        },
        "cosmic_horror": {
            "id": "cosmic_horror",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A being from beyond the stars, its form incomprehensible to the mortal mind.",
            "extra_tags": ["eldritch", "terror", "colossal"],
            "base_stats": {
                "strength": 30,
                "agility": 10,
                "endurance": 50,
                "intelligence": 25,
                "wisdom": 25,
                "men": 60,
                "perception": 20,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "special_unique", "attack_aoe"],
        },
        "gate_of_madness": {
            "id": "gate_of_madness",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "Not a creature, but a living portal to the void, spawning horrors and driving viewers insane.",
            "extra_tags": ["portal", "summoner", "stationary"],
            "base_stats": {
                "strength": 0,
                "agility": 0,
                "endurance": 60,
                "intelligence": 20,
                "wisdom": 20,
                "men": 100,
                "perception": 20,
                "charisma": 1,
                "luck": 20,
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "summon_minion", "debuff_weaken", "debuff_stun"],
        },
    },
}
