"""
СЕМЕЙСТВО: АНГЕЛЫ (Свет, порядок, контроль)
===========================================
Логика: свет -> порядок -> контроль
"""

from ..monster_structs import MonsterFamily

ANGELS_FAMILY: MonsterFamily = {
    "id": "angelic_host",
    "archetype": "humanoid",
    "organization_type": "legion",
    "default_tags": ["angel", "light", "holy", "order"],
    "hierarchy": {
        "minions": ["cherubim", "light_warden", "guardian_spirit", "seraphic_scout"],
        "veterans": ["angelic_soldier", "swordbearer", "lumina_knight", "sky_sentinel"],
        "elites": ["seraph_knight", "high_guardian", "light_marshal", "celestial_champion"],
        "boss": ["archangel", "radiant_overlord", "dawnbringer", "seraphic_lord"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) ---
        "cherubim": {
            "id": "cherubim",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A small, winged figure with a child-like face. Radiates a soft glow.",
            "extra_tags": ["support", "healer", "ranged"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 4,
                "intelligence": 8,
                "wisdom": 8,
                "men": 10,
                "perception": 10,
                "charisma": 10,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "buff_heal", "buff_rage"],
        },
        "light_warden": {
            "id": "light_warden",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating construct of light and armor. Guards sacred places.",
            "extra_tags": ["construct", "guardian"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 4,
                "men": 10,
                "perception": 12,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "spear", "chest_armor": "plate_chest"},
            "skills": ["attack_ranged", "buff_defense"],
        },
        "guardian_spirit": {
            "id": "guardian_spirit",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A translucent spirit in the shape of a warrior. Immune to fear.",
            "extra_tags": ["spirit", "ethereal"],
            "base_stats": {
                "strength": 6,
                "agility": 10,
                "endurance": 6,
                "intelligence": 6,
                "wisdom": 6,
                "men": 15,
                "perception": 10,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "sword"},
            "skills": ["attack_basic", "buff_defense"],
        },
        "seraphic_scout": {
            "id": "seraphic_scout",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A swift angel with four wings. Watches from above.",
            "extra_tags": ["scout", "fast", "flying"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 6,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 16,
                "charisma": 6,
                "luck": 8,
            },
            "fixed_loadout": {"main_hand": "bow"},
            "skills": ["attack_ranged"],
        },
        # --- 2. Стражи / Бойцы (Veterans) ---
        "angelic_soldier": {
            "id": "angelic_soldier",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A disciplined warrior of light in shining armor.",
            "extra_tags": ["soldier", "infantry", "shield"],
            "base_stats": {
                "strength": 12,
                "agility": 10,
                "endurance": 12,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 10,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
            },
            "skills": ["attack_heavy", "debuff_stun", "buff_defense"],
        },
        "swordbearer": {
            "id": "swordbearer",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "An angel wielding a massive flaming sword.",
            "extra_tags": ["fire", "greatsword"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 10,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 10,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest"},
            "skills": ["debuff_burn", "attack_aoe"],
        },
        "lumina_knight": {
            "id": "lumina_knight",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A knight whose armor is made of solidified light.",
            "extra_tags": ["knight", "light", "tank"],
            "base_stats": {
                "strength": 12,
                "agility": 12,
                "endurance": 14,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 12,
                "charisma": 10,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "mace", "off_hand": "shield"},
            "skills": ["debuff_blind", "attack_aoe", "buff_heal"],
        },
        "sky_sentinel": {
            "id": "sky_sentinel",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "An angel with powerful wings and a long spear. Dives into battle.",
            "extra_tags": ["flying", "sentinel"],
            "base_stats": {
                "strength": 14,
                "agility": 14,
                "endurance": 12,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 14,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "spear", "chest_armor": "plate_chest"},
            "skills": ["attack_heavy", "attack_pierce", "attack_aoe"],
        },
        # --- 3. Элита (Elites) ---
        "seraph_knight": {
            "id": "seraph_knight",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A high-ranking angel with six wings. Wields dual blades of light.",
            "extra_tags": ["seraph", "knight", "dual_wield"],
            "base_stats": {
                "strength": 16,
                "agility": 16,
                "endurance": 16,
                "intelligence": 10,
                "wisdom": 10,
                "men": 20,
                "perception": 14,
                "charisma": 12,
                "luck": 8,
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "sword", "chest_armor": "plate_chest"},
            "skills": ["attack_fast", "debuff_burn", "attack_execute"],
        },
        "high_guardian": {
            "id": "high_guardian",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A towering figure in golden armor. An immovable object.",
            "extra_tags": ["guardian", "heavy_armor", "unbreakable"],
            "base_stats": {
                "strength": 20,
                "agility": 8,
                "endurance": 22,
                "intelligence": 8,
                "wisdom": 8,
                "men": 20,
                "perception": 12,
                "charisma": 10,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "warhammer", "off_hand": "tower_shield", "chest_armor": "plate_chest"},
            "skills": ["buff_defense", "attack_heavy", "buff_defense"],
        },
        "light_marshal": {
            "id": "light_marshal",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A commander of the angelic host. Inspires allies with his presence.",
            "extra_tags": ["marshal", "commander", "aura"],
            "base_stats": {
                "strength": 16,
                "agility": 12,
                "endurance": 18,
                "intelligence": 14,
                "wisdom": 14,
                "men": 25,
                "perception": 16,
                "charisma": 20,
                "luck": 10,
            },
            "fixed_loadout": {"main_hand": "sword", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["buff_rage", "buff_rage", "buff_heal"],
        },
        "celestial_champion": {
            "id": "celestial_champion",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "The champion of the heavens. A perfect warrior.",
            "extra_tags": ["champion", "celestial"],
            "base_stats": {
                "strength": 22,
                "agility": 14,
                "endurance": 20,
                "intelligence": 10,
                "wisdom": 10,
                "men": 20,
                "perception": 14,
                "charisma": 15,
                "luck": 10,
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest"},
            "skills": ["attack_aoe", "attack_execute", "buff_heal"],
        },
        # --- 4. Архангелы / Боссы (Bosses) ---
        "archangel": {
            "id": "archangel",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A being of pure light and power. His voice sounds like thunder.",
            "extra_tags": ["archangel", "leader"],
            "base_stats": {
                "strength": 25,
                "agility": 20,
                "endurance": 30,
                "intelligence": 25,
                "wisdom": 25,
                "men": 50,
                "perception": 25,
                "charisma": 30,
                "luck": 15,
            },
            "fixed_loadout": {"main_hand": "flaming_sword"},
            "skills": ["attack_aoe", "attack_execute", "summon_minion"],
        },
        "radiant_overlord": {
            "id": "radiant_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A ruler of a celestial realm. Blinds enemies with his radiance.",
            "extra_tags": ["overlord", "radiant", "ruler"],
            "base_stats": {
                "strength": 30,
                "agility": 15,
                "endurance": 40,
                "intelligence": 30,
                "wisdom": 30,
                "men": 60,
                "perception": 30,
                "charisma": 35,
                "luck": 20,
            },
            "fixed_loadout": {"main_hand": "scepter"},
            "skills": ["debuff_blind", "attack_aoe", "special_unique", "attack_execute"],
        },
        "dawnbringer": {
            "id": "dawnbringer",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "The herald of the dawn. Brings hope to allies and destruction to enemies.",
            "extra_tags": ["herald", "dawn"],
            "base_stats": {
                "strength": 35,
                "agility": 25,
                "endurance": 35,
                "intelligence": 20,
                "wisdom": 20,
                "men": 40,
                "perception": 25,
                "charisma": 40,
                "luck": 25,
            },
            "fixed_loadout": {"main_hand": "morningstar"},
            "skills": ["attack_heavy", "attack_aoe", "buff_heal", "buff_rage"],
        },
        "seraphic_lord": {
            "id": "seraphic_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "The highest of angels. Has six wings and eyes burning with holy fire.",
            "extra_tags": ["seraph", "godlike"],
            "base_stats": {
                "strength": 40,
                "agility": 30,
                "endurance": 50,
                "intelligence": 40,
                "wisdom": 40,
                "men": 100,
                "perception": 40,
                "charisma": 50,
                "luck": 30,
            },
            "fixed_loadout": {"main_hand": "sword_of_light"},
            "skills": ["special_unique", "special_unique", "special_unique"],
        },
    },
}
