"""
СЕМЕЙСТВО: МЕХАНИЗМЫ (Точность, пар, логика)
==============================================
Логика: анализ -> исполнение -> самоуничтожение
"""

from ..monster_structs import MonsterFamily

CLOCKWORKS_FAMILY: MonsterFamily = {
    "id": "clockwork_army",
    "archetype": "construct",
    "organization_type": "legion",
    "default_tags": ["construct", "clockwork", "fearless", "steam"],
    "hierarchy": {
        "minions": ["spider_bot", "worker_drone", "repair_unit"],
        "veterans": ["steam_guard", "gunner_bot", "shock_trooper"],
        "elites": ["centurion_prime", "tesla_coil", "siege_automaton"],
        "boss": ["the_architect", "prime_engine", "omega_frame"],
    },
    "variants": {
        # --- 1. Мелкие дроны (Minions) [Tier 3-6] ---
        "spider_bot": {
            "id": "spider_bot",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A small, multi-legged automaton that scuttles across the floor.",
            "extra_tags": ["spider_bot", "fast"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 6,
                "intelligence": 3,
                "wisdom": 1,
                "men": 10,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "debuff_slow"],
        },
        "worker_drone": {
            "id": "worker_drone",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A simple bipedal automaton with tools for hands. Not designed for combat.",
            "extra_tags": ["worker", "weak"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 1,
                "men": 10,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_armor_break"],
        },
        "repair_unit": {
            "id": "repair_unit",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A small drone equipped with tools to repair other automatons.",
            "extra_tags": ["support", "healer"],
            "base_stats": {
                "strength": 4,
                "agility": 10,
                "endurance": 6,
                "intelligence": 5,
                "wisdom": 5,
                "men": 10,
                "perception": 12,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_heal", "buff_defense"],
        },
        # --- 2. Боевые единицы (Veterans) [Tier 3-7] ---
        "steam_guard": {
            "id": "steam_guard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A humanoid automaton powered by steam, wielding a large shield.",
            "extra_tags": ["guard", "shield", "steam"],
            "base_stats": {
                "strength": 12,
                "agility": 8,
                "endurance": 14,
                "intelligence": 3,
                "wisdom": 1,
                "men": 15,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {"off_hand": "shield"},
            "skills": ["buff_defense", "attack_heavy"],
        },
        "gunner_bot": {
            "id": "gunner_bot",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "An automaton with a built-in crossbow or firearm.",
            "extra_tags": ["ranged", "gunner"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 1,
                "men": 12,
                "perception": 14,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_ranged"],
        },
        "shock_trooper": {
            "id": "shock_trooper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A fast automaton designed for flanking, equipped with electrified blades.",
            "extra_tags": ["fast", "shock"],
            "base_stats": {
                "strength": 10,
                "agility": 14,
                "endurance": 10,
                "intelligence": 3,
                "wisdom": 1,
                "men": 10,
                "perception": 12,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_fast", "debuff_stun"],
        },
        # --- 3. Элита (Elites) [Tier 4-7] ---
        "centurion_prime": {
            "id": "centurion_prime",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A large, heavily armored automaton that leads squads into battle.",
            "extra_tags": ["leader", "heavy_armor"],
            "base_stats": {
                "strength": 18,
                "agility": 8,
                "endurance": 20,
                "intelligence": 6,
                "wisdom": 2,
                "men": 20,
                "perception": 14,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "greatsword"},
            "skills": ["attack_aoe", "buff_rage", "buff_defense"],
        },
        "tesla_coil": {
            "id": "tesla_coil",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A walking tesla coil that arcs electricity to nearby targets.",
            "extra_tags": ["tesla", "aoe", "shock"],
            "base_stats": {
                "strength": 10,
                "agility": 6,
                "endurance": 16,
                "intelligence": 5,
                "wisdom": 1,
                "men": 25,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_aoe", "debuff_stun"],
        },
        "siege_automaton": {
            "id": "siege_automaton",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A massive, slow-moving automaton with a cannon for an arm.",
            "extra_tags": ["siege", "heavy"],
            "base_stats": {
                "strength": 20,
                "agility": 4,
                "endurance": 24,
                "intelligence": 3,
                "wisdom": 1,
                "men": 20,
                "perception": 12,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_heavy", "attack_aoe"],
        },
        # --- 4. Архитекторы (Bosses) [Tier 5-7] ---
        "the_architect": {
            "id": "the_architect",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "The central intelligence controlling the automatons. A complex brain in a jar.",
            "extra_tags": ["leader", "mage"],
            "base_stats": {
                "strength": 5,
                "agility": 5,
                "endurance": 30,
                "intelligence": 35,
                "wisdom": 20,
                "men": 50,
                "perception": 30,
                "charisma": 10,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "buff_rage", "special_unique", "attack_aoe"],
        },
        "prime_engine": {
            "id": "prime_engine",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "The colossal, walking factory that produces other automatons.",
            "extra_tags": ["factory", "summoner"],
            "base_stats": {
                "strength": 30,
                "agility": 2,
                "endurance": 50,
                "intelligence": 10,
                "wisdom": 5,
                "men": 40,
                "perception": 15,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "summon_minion", "attack_aoe", "buff_defense"],
        },
        "omega_frame": {
            "id": "omega_frame",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "The ultimate combat automaton, equipped with an arsenal of deadly weapons.",
            "extra_tags": ["war_machine", "heavy_armor"],
            "base_stats": {
                "strength": 40,
                "agility": 10,
                "endurance": 40,
                "intelligence": 15,
                "wisdom": 5,
                "men": 30,
                "perception": 20,
                "charisma": 5,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_execute", "attack_aoe", "attack_ranged", "attack_heavy"],
        },
    },
}
