"""
СЕМЕЙСТВО: ДРАКОНЫ (Территория и доминирование)
===============================================
Логика: территория -> давление -> доминирование
"""

from ..monster_structs import MonsterFamily

DRAGONS_FAMILY: MonsterFamily = {
    "id": "dragon_lair",
    "archetype": "beast",
    "organization_type": "solitary",
    "default_tags": ["beast", "dragon", "scale", "fire"],
    "hierarchy": {
        "minions": ["drake_whelp", "wingless_drake"],
        "veterans": ["sky_drake", "ash_drake"],
        "elites": ["ancient_drake", "elemental_drake"],
        "boss": ["dragon_lord", "world_dragon"],
    },
    "variants": {
        # --- 1. Молодняк (Minions) ---
        "drake_whelp": {
            "id": "drake_whelp",
            "role": "minion",
            "cost": 20,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A small dragon, barely larger than a dog. Snaps its jaws aggressively.",
            "extra_tags": ["young", "fire"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 8,
                "intelligence": 4,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "debuff_burn"],
        },
        "wingless_drake": {
            "id": "wingless_drake",
            "role": "minion",
            "cost": 20,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A muscular, flightless drake. Charges with reckless abandon.",
            "extra_tags": ["grounded", "brute"],
            "base_stats": {
                "strength": 12,
                "agility": 8,
                "endurance": 12,
                "intelligence": 3,
                "wisdom": 3,
                "men": 8,
                "perception": 8,
                "charisma": 4,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe"],
        },
        # --- 2. Охотники (Veterans) ---
        "sky_drake": {
            "id": "sky_drake",
            "role": "veteran",
            "cost": 50,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A sleek drake with wide wings. Dives from the sky.",
            "extra_tags": ["flying", "fast"],
            "base_stats": {
                "strength": 14,
                "agility": 16,
                "endurance": 14,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 14,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "attack_aoe", "attack_heavy"],
        },
        "ash_drake": {
            "id": "ash_drake",
            "role": "veteran",
            "cost": 50,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A drake covered in soot and ash. Its scales glow with inner heat.",
            "extra_tags": ["fire", "ash"],
            "base_stats": {
                "strength": 16,
                "agility": 12,
                "endurance": 16,
                "intelligence": 5,
                "wisdom": 5,
                "men": 12,
                "perception": 12,
                "charisma": 6,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_blind", "debuff_burn"],
        },
        # --- 3. Доминирующие (Elites) ---
        "ancient_drake": {
            "id": "ancient_drake",
            "role": "elite",
            "cost": 150,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "A massive drake with thick, scarred scales. Moves with heavy purpose.",
            "extra_tags": ["ancient", "heavy_armor", "tough"],
            "base_stats": {
                "strength": 20,
                "agility": 8,
                "endurance": 22,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 12,
                "charisma": 10,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_weaken", "buff_defense"],
        },
        "elemental_drake": {
            "id": "elemental_drake",
            "role": "elite",
            "cost": 150,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "A drake infused with raw elemental energy (fire, ice, or lightning).",
            "extra_tags": ["elemental", "magic"],
            "base_stats": {
                "strength": 18,
                "agility": 14,
                "endurance": 18,
                "intelligence": 10,
                "wisdom": 10,
                "men": 20,
                "perception": 14,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_aoe", "attack_aoe"],
        },
        # --- 4. Вершины (Bosses) ---
        "dragon_lord": {
            "id": "dragon_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 8,
            "max_tier": 11,
            "narrative_hint": "A true dragon of immense size and intelligence. Rules the region.",
            "extra_tags": ["lord", "leader", "ancient"],
            "base_stats": {
                "strength": 30,
                "agility": 15,
                "endurance": 35,
                "intelligence": 20,
                "wisdom": 20,
                "men": 40,
                "perception": 20,
                "charisma": 25,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_aoe", "attack_heavy", "debuff_weaken"],
        },
        "world_dragon": {
            "id": "world_dragon",
            "role": "boss",
            "cost": 600,
            "min_tier": 8,
            "max_tier": 11,
            "narrative_hint": "A creature so large it is mistaken for a mountain range. Its awakening changes the world.",
            "extra_tags": ["colossal", "world_ender"],
            "base_stats": {
                "strength": 50,
                "agility": 10,
                "endurance": 60,
                "intelligence": 30,
                "wisdom": 30,
                "men": 60,
                "perception": 25,
                "charisma": 30,
                "luck": 20,
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "special_unique", "special_unique"],
        },
    },
}
