"""
СЕМЕЙСТВО: ЭЛЕМЕНТАЛИ (Среда и разрушение)
==========================================
Логика: среда -> форма -> разрушение
"""

from ..monster_structs import MonsterFamily

ELEMENTALS_FAMILY: MonsterFamily = {
    "id": "elemental_rift",
    "archetype": "construct",
    "organization_type": "solitary",
    "default_tags": ["elemental", "magic", "chaos"],
    "hierarchy": {
        "minions": ["elemental_spark", "elemental_wisp"],
        "veterans": ["fire_elemental", "ice_elemental"],
        "elites": ["greater_elemental", "raging_elemental"],
        "boss": ["elemental_lord", "primal_avatar"],
    },
    "variants": {
        # --- 1. Проявления (Minions) ---
        "elemental_spark": {
            "id": "elemental_spark",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A tiny, flickering mote of elemental energy. Moves erratically.",
            "extra_tags": ["spark", "weak"],
            "base_stats": {
                "strength": 2,
                "agility": 14,
                "endurance": 2,
                "intelligence": 1,
                "wisdom": 1,
                "men": 10,
                "perception": 6,
                "charisma": 1,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged"],
        },
        "elemental_wisp": {
            "id": "elemental_wisp",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A floating ball of light and energy. Seems curious but dangerous.",
            "extra_tags": ["wisp", "energy"],
            "base_stats": {
                "strength": 3,
                "agility": 12,
                "endurance": 4,
                "intelligence": 2,
                "wisdom": 2,
                "men": 12,
                "perception": 10,
                "charisma": 5,
                "luck": 8,
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "debuff_blind"],
        },
        # --- 2. Стабильные формы (Veterans) ---
        "fire_elemental": {
            "id": "fire_elemental",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A humanoid shape made of roaring flames. Burns everything it touches.",
            "extra_tags": ["fire", "burn"],
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 4,
                "men": 15,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "debuff_burn", "attack_heavy"],
        },
        "ice_elemental": {
            "id": "ice_elemental",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A jagged construct of ice and snow. Radiates intense cold.",
            "extra_tags": ["ice", "cold", "freeze"],
            "base_stats": {
                "strength": 12,
                "agility": 6,
                "endurance": 14,
                "intelligence": 4,
                "wisdom": 4,
                "men": 15,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "debuff_stun", "attack_heavy"],
        },
        # --- 3. Усиленные (Elites) ---
        "greater_elemental": {
            "id": "greater_elemental",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A massive elemental, its form stable and imposing. Commands the lesser spirits.",
            "extra_tags": ["greater", "leader"],
            "base_stats": {
                "strength": 16,
                "agility": 8,
                "endurance": 18,
                "intelligence": 8,
                "wisdom": 8,
                "men": 20,
                "perception": 12,
                "charisma": 10,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "summon_minion", "attack_heavy"],
        },
        "raging_elemental": {
            "id": "raging_elemental",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "An elemental in a state of chaotic flux, exploding with power.",
            "extra_tags": ["raging", "unstable", "explosive"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 14,
                "intelligence": 6,
                "wisdom": 6,
                "men": 25,
                "perception": 10,
                "charisma": 1,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["explode_on_death", "special_unique", "attack_aoe"],
        },
        # --- 4. Аватары (Bosses) ---
        "elemental_lord": {
            "id": "elemental_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A god-like entity composed of pure elemental force. Rules a plane of existence.",
            "extra_tags": ["lord", "ancient", "ruler"],
            "base_stats": {
                "strength": 25,
                "agility": 15,
                "endurance": 30,
                "intelligence": 20,
                "wisdom": 20,
                "men": 50,
                "perception": 20,
                "charisma": 20,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "summon_minion", "special_unique"],
        },
        "primal_avatar": {
            "id": "primal_avatar",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "The living embodiment of nature's wrath. A storm given form.",
            "extra_tags": ["primal", "avatar", "nature"],
            "base_stats": {
                "strength": 30,
                "agility": 20,
                "endurance": 40,
                "intelligence": 15,
                "wisdom": 25,
                "men": 60,
                "perception": 25,
                "charisma": 15,
                "luck": 15,
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "attack_aoe", "attack_aoe", "attack_aoe"],
        },
    },
}
