"""
СЕМЕЙСТВО: ГОБЛИНЫ (Техно-хаос и выживание)
=========================================
Логика: хитрость -> инструменты -> взрыв
"""

from ..monster_structs import MonsterFamily

GOBLINS_FAMILY: MonsterFamily = {
    "id": "goblin_tribe",
    "archetype": "humanoid",
    "organization_type": "horde",
    "default_tags": ["goblin", "small", "cunning", "tinkerer"],
    "hierarchy": {
        "minions": ["goblin_sneak", "goblin_scavenger"],
        "veterans": ["goblin_spearman", "goblin_slinger"],
        "elites": ["goblin_tinkerer", "goblin_bomber"],
        "boss": ["goblin_chief", "scrap_king"],
    },
    "variants": {
        # --- 1. Мелочь (Minions) [Tier 0-4] ---
        "goblin_sneak": {
            "id": "goblin_sneak",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A small goblin with a hooded cloak and a pair of sharp daggers, moves silently.",
            "extra_tags": ["stealth", "assassin"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 8,
                "intelligence": 7,
                "wisdom": 5,
                "men": 5,
                "perception": 12,
                "charisma": 3,
                "luck": 10,
            },
            "fixed_loadout": {"main_hand": "dagger", "off_hand": "dagger", "chest_garment": "shirt"},
            "skills": ["attack_heavy", "stealth"],
        },
        "goblin_scavenger": {
            "id": "goblin_scavenger",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A goblin carrying a large, overflowing backpack. Wields a simple club.",
            "extra_tags": ["scavenger", "hoarder"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 10,
                "intelligence": 6,
                "wisdom": 6,
                "men": 5,
                "perception": 10,
                "charisma": 4,
                "luck": 8,
            },
            "fixed_loadout": {"main_hand": "mace", "chest_garment": "shirt"},
            "skills": ["debuff_armor_break"],
        },
        # --- 2. Бойцы (Veterans) [Tier 0-5] ---
        "goblin_spearman": {
            "id": "goblin_spearman",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 5,
            "narrative_hint": "A disciplined goblin with a long spear and a crude wooden shield.",
            "extra_tags": ["infantry", "shield"],
            "base_stats": {
                "strength": 10,
                "agility": 10,
                "endurance": 11,
                "intelligence": 5,
                "wisdom": 5,
                "men": 6,
                "perception": 9,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "spear", "off_hand": "shield", "chest_armor": "jerkin"},
            "skills": ["attack_pierce", "buff_defense"],
        },
        "goblin_slinger": {
            "id": "goblin_slinger",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A fast goblin with a sling, constantly moving and throwing rocks.",
            "extra_tags": ["ranged", "fast"],
            "base_stats": {
                "strength": 5,
                "agility": 13,
                "endurance": 9,
                "intelligence": 6,
                "wisdom": 7,
                "men": 5,
                "perception": 11,
                "charisma": 4,
                "luck": 7,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged"],
        },
        # --- 3. Инженеры (Elites) [Tier 2-6] ---
        "goblin_tinkerer": {
            "id": "goblin_tinkerer",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with goggles and a belt full of tools. Throws caltrops and sets traps.",
            "extra_tags": ["engineer", "trapper"],
            "base_stats": {
                "strength": 7,
                "agility": 12,
                "endurance": 10,
                "intelligence": 13,
                "wisdom": 8,
                "men": 7,
                "perception": 12,
                "charisma": 6,
                "luck": 9,
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "apron"},
            "skills": ["special_trap", "debuff_slow"],
        },
        "goblin_bomber": {
            "id": "goblin_bomber",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with a manic grin and a sack of crude explosives.",
            "extra_tags": ["bomber", "explosives", "reckless"],
            "base_stats": {
                "strength": 8,
                "agility": 11,
                "endurance": 11,
                "intelligence": 12,
                "wisdom": 6,
                "men": 8,
                "perception": 10,
                "charisma": 5,
                "luck": 10,
            },
            "fixed_loadout": {"chest_armor": "jerkin"},
            "skills": ["attack_aoe", "explode_on_death"],
        },
        # --- 4. Вожди (Bosses) [Tier 3-7] ---
        "goblin_chief": {
            "id": "goblin_chief",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A larger, smarter goblin wearing a crude crown and better armor. Shouts commands.",
            "extra_tags": ["leader", "commander"],
            "base_stats": {
                "strength": 15,
                "agility": 12,
                "endurance": 16,
                "intelligence": 10,
                "wisdom": 9,
                "men": 10,
                "perception": 12,
                "charisma": 12,
                "luck": 8,
            },
            "fixed_loadout": {"main_hand": "battle_axe", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["buff_rage", "attack_aoe", "attack_execute"],
        },
        "scrap_king": {
            "id": "scrap_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A huge goblin sitting on a throne of junk, wearing a makeshift power armor.",
            "extra_tags": ["king", "heavy_armor", "engineer"],
            "base_stats": {
                "strength": 20,
                "agility": 8,
                "endurance": 22,
                "intelligence": 14,
                "wisdom": 10,
                "men": 12,
                "perception": 14,
                "charisma": 15,
                "luck": 5,
            },
            "fixed_loadout": {
                "main_hand": "warhammer",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "arms_armor": "gauntlets",
                "legs_armor": "greaves",
            },
            "skills": ["attack_ranged", "debuff_stun", "buff_rage"],
        },
    },
}
