"""
СЕМЕЙСТВО: НАСЕКОМЫЕ (Биомасса и защита)
========================================
Логика: броня -> кислота -> рой
"""

from ..monster_structs import MonsterFamily

INSECTS_FAMILY: MonsterFamily = {
    "id": "insect_hive",
    "archetype": "beast",
    "organization_type": "swarm",
    "default_tags": ["beast", "insect", "chitin", "acid"],
    "hierarchy": {
        "minions": ["drone_bug", "burrower", "forager"],
        "veterans": ["acid_spitter", "shell_guard", "ripper"],
        "elites": ["hive_caster", "spore_bearer"],
        "boss": ["insect_queen", "ancient_broodmother"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) ---
        "drone_bug": {
            "id": "drone_bug",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A simple worker insect with mandibles for carrying loads. Ignores threats until attacked.",
            "extra_tags": ["worker", "weak"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 10,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 6,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "burrower": {
            "id": "burrower",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "An insect with massive shovel-like claws. Moves underground.",
            "extra_tags": ["digger", "surprise"],
            "base_stats": {
                "strength": 10,
                "agility": 5,
                "endurance": 12,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 4,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy"],
        },
        "forager": {
            "id": "forager",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A fast insect with sensitive antennae. Scouts for food.",
            "extra_tags": ["scout", "fast"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 2,
                "men": 5,
                "perception": 14,
                "charisma": 1,
                "luck": 8,
            },
            "fixed_loadout": {},
            "skills": [],
        },
        # --- 2. Охотники / Бойцы (Veterans) ---
        "acid_spitter": {
            "id": "acid_spitter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An insect with a pulsating green sac on its back. Spits corrosive acid.",
            "extra_tags": ["ranged", "acid"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 2,
                "men": 5,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_armor_break", "debuff_armor_break"],
        },
        "shell_guard": {
            "id": "shell_guard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A heavily armored insect. Its chitin is thick as plate mail.",
            "extra_tags": ["tank", "heavy_armor"],
            "base_stats": {
                "strength": 14,
                "agility": 4,
                "endurance": 18,
                "intelligence": 2,
                "wisdom": 2,
                "men": 8,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "debuff_stun"],
        },
        "ripper": {
            "id": "ripper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An insect with scythe-like forelimbs designed for combat.",
            "extra_tags": ["melee", "sharp"],
            "base_stats": {
                "strength": 12,
                "agility": 12,
                "endurance": 10,
                "intelligence": 2,
                "wisdom": 2,
                "men": 6,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_bleed", "attack_fast"],
        },
        # --- 3. Элита (Elites) ---
        "hive_caster": {
            "id": "hive_caster",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A strange insect that emits a humming sound. Glows with bio-luminescence.",
            "extra_tags": ["support", "caster", "aura"],
            "base_stats": {
                "strength": 8,
                "agility": 8,
                "endurance": 12,
                "intelligence": 10,
                "wisdom": 10,
                "men": 15,
                "perception": 12,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "buff_rage", "buff_defense"],
        },
        "spore_bearer": {
            "id": "spore_bearer",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A bloated insect covered in fungal growths. Releases clouds of spores.",
            "extra_tags": ["spores", "poison", "debuff"],
            "base_stats": {
                "strength": 10,
                "agility": 6,
                "endurance": 16,
                "intelligence": 4,
                "wisdom": 6,
                "men": 10,
                "perception": 8,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_blind", "debuff_poison"],
        },
        # --- 4. Королевы / Боссы (Bosses) ---
        "insect_queen": {
            "id": "insect_queen",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "The massive mother of the hive. Immobile but terrifyingly powerful.",
            "extra_tags": ["queen", "leader", "summoner"],
            "base_stats": {
                "strength": 20,
                "agility": 5,
                "endurance": 30,
                "intelligence": 15,
                "wisdom": 15,
                "men": 25,
                "perception": 20,
                "charisma": 20,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "summon_minion", "debuff_weaken", "debuff_armor_break"],
        },
        "ancient_broodmother": {
            "id": "ancient_broodmother",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A creature as old as the caves themselves. Her chitin is like stone.",
            "extra_tags": ["ancient", "heavy_armor", "tough"],
            "base_stats": {
                "strength": 25,
                "agility": 8,
                "endurance": 40,
                "intelligence": 18,
                "wisdom": 18,
                "men": 30,
                "perception": 20,
                "charisma": 15,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_execute", "debuff_poison", "buff_defense"],
        },
    },
}
