"""
СЕМЕЙСТВО: РАСТЕНИЯ / ЖИВОЙ ЛЕС (Регенерация, контроль, яд)
==========================================================
Логика: рост -> опутывание -> поглощение
"""

from ..monster_structs import MonsterFamily

PLANTS_FAMILY: MonsterFamily = {
    "id": "living_forest",
    "archetype": "beast",
    "organization_type": "horde",
    "default_tags": ["plant", "nature", "poison", "regenerating"],
    "hierarchy": {
        "minions": ["vine_lasher", "spore_puff", "sapling"],
        "veterans": ["thorn_spitter", "carnivorous_plant", "needle_bush"],
        "elites": ["dryad_guardian", "bark_skin", "root_strangler"],
        "boss": ["ancient_treant", "heart_of_forest", "rotting_willow"],
    },
    "variants": {
        # --- 1. Поросль (Minions) [Tier 1-4] ---
        "vine_lasher": {
            "id": "vine_lasher",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A writhing mass of vines that lashes out at anything moving.",
            "extra_tags": ["vine", "weak"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 6,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "debuff_slow"],
        },
        "spore_puff": {
            "id": "spore_puff",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A small fungus that explodes into a cloud of choking dust when hit.",
            "extra_tags": ["fungus", "poison"],
            "base_stats": {
                "strength": 2,
                "agility": 4,
                "endurance": 8,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 4,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["explode_on_death", "debuff_poison"],
        },
        "sapling": {
            "id": "sapling",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A young tree warrior, barely waist-high but with hard bark.",
            "extra_tags": ["tree", "sturdy"],
            "base_stats": {
                "strength": 8,
                "agility": 4,
                "endurance": 10,
                "intelligence": 2,
                "wisdom": 2,
                "men": 10,
                "perception": 6,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "buff_defense"],
        },
        # --- 2. Заросли (Veterans) [Tier 1-5] ---
        "thorn_spitter": {
            "id": "thorn_spitter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A plant with a tube-like flower that shoots sharp thorns.",
            "extra_tags": ["ranged", "piercing"],
            "base_stats": {
                "strength": 6,
                "agility": 8,
                "endurance": 10,
                "intelligence": 2,
                "wisdom": 2,
                "men": 5,
                "perception": 12,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_pierce"],
        },
        "carnivorous_plant": {
            "id": "carnivorous_plant",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A massive venus flytrap capable of swallowing a man whole.",
            "extra_tags": ["trap", "acid"],
            "base_stats": {
                "strength": 14,
                "agility": 4,
                "endurance": 14,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_armor_break"],
        },
        "needle_bush": {
            "id": "needle_bush",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A bush covered in thousands of needles. Can shake them loose at enemies.",
            "extra_tags": ["aoe", "defense"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 12,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "buff_reflect"],
        },
        # --- 3. Стражи Леса (Elites) [Tier 2-6] ---
        "dryad_guardian": {
            "id": "dryad_guardian",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A humanoid spirit of the forest, wielding nature magic.",
            "extra_tags": ["magic", "spirit"],
            "base_stats": {
                "strength": 8,
                "agility": 14,
                "endurance": 10,
                "intelligence": 12,
                "wisdom": 14,
                "men": 15,
                "perception": 14,
                "charisma": 12,
                "luck": 10,
            },
            "fixed_loadout": {"main_hand": "staff"},
            "skills": ["buff_heal", "debuff_stun", "attack_ranged"],
        },
        "bark_skin": {
            "id": "bark_skin",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A humanoid figure made of incredibly thick, ancient bark.",
            "extra_tags": ["tank", "heavy_armor"],
            "base_stats": {
                "strength": 18,
                "agility": 6,
                "endurance": 20,
                "intelligence": 4,
                "wisdom": 8,
                "men": 20,
                "perception": 10,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "attack_heavy", "buff_heal"],
        },
        "root_strangler": {
            "id": "root_strangler",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A mass of roots that moves underground and erupts to crush prey.",
            "extra_tags": ["ambush", "control"],
            "base_stats": {
                "strength": 16,
                "agility": 8,
                "endurance": 16,
                "intelligence": 6,
                "wisdom": 6,
                "men": 10,
                "perception": 16,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["special_trap", "attack_aoe", "debuff_slow"],
        },
        # --- 4. Сердце Леса (Bosses) [Tier 3-7] ---
        "ancient_treant": {
            "id": "ancient_treant",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A walking tree as tall as a tower. Its skin is stone, its wrath is slow but inevitable.",
            "extra_tags": ["ancient", "colossal"],
            "base_stats": {
                "strength": 35,
                "agility": 4,
                "endurance": 40,
                "intelligence": 15,
                "wisdom": 25,
                "men": 40,
                "perception": 15,
                "charisma": 10,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_heavy", "buff_defense", "summon_minion"],
        },
        "heart_of_forest": {
            "id": "heart_of_forest",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A pulsating core of magical energy protected by layers of wood and vines.",
            "extra_tags": ["magic", "stationary"],
            "base_stats": {
                "strength": 10,
                "agility": 0,
                "endurance": 50,
                "intelligence": 30,
                "wisdom": 30,
                "men": 60,
                "perception": 30,
                "charisma": 20,
                "luck": 20,
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "buff_heal", "special_unique", "attack_aoe"],
        },
        "rotting_willow": {
            "id": "rotting_willow",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A corrupted tree dripping with black ichor. Spreads decay wherever it walks.",
            "extra_tags": ["undead_plant", "poison", "decay"],
            "base_stats": {
                "strength": 25,
                "agility": 8,
                "endurance": 35,
                "intelligence": 10,
                "wisdom": 10,
                "men": 30,
                "perception": 15,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_weaken", "attack_lifesteal", "attack_aoe"],
        },
    },
}
