"""
СЕМЕЙСТВО: КРЫСЫ (Численность, заражение, давление массой)
=========================================================
Логика: количество -> паника -> болезнь
"""

from ..monster_structs import MonsterFamily

RATS_FAMILY: MonsterFamily = {
    "id": "rat_swarm",
    "archetype": "beast",
    "organization_type": "swarm",
    "default_tags": ["beast", "rat", "disease", "swarm"],
    "hierarchy": {
        "minions": ["sewer_rat", "scavenger_rat", "swarm_rat"],
        "veterans": ["tunnel_rat", "pack_rat", "screecher"],
        "elites": ["plague_rat", "rotfang", "blight_carrier"],
        "boss": ["rat_brute", "brood_alpha", "rat_king"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [Tier 0-3] ---
        "sewer_rat": {
            "id": "sewer_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A dirty, wet rat with matted fur. Scavenges for food.",
            "extra_tags": ["common", "weak"],
            "base_stats": {
                "strength": 4,
                "agility": 10,
                "endurance": 5,
                "intelligence": 2,
                "wisdom": 2,
                "men": 5,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "scavenger_rat": {
            "id": "scavenger_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A rat dragging a piece of refuse. Will fight to protect its treasure.",
            "extra_tags": ["scavenger", "hoarder"],
            "base_stats": {
                "strength": 6,
                "agility": 8,
                "endurance": 7,
                "intelligence": 3,
                "wisdom": 2,
                "men": 5,
                "perception": 10,
                "charisma": 1,
                "luck": 8,
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_basic"],
        },
        "swarm_rat": {
            "id": "swarm_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "One of hundreds. Individually weak, but terrifying in numbers.",
            "extra_tags": ["swarm", "frenzied"],
            "base_stats": {
                "strength": 5,
                "agility": 14,
                "endurance": 5,
                "intelligence": 1,
                "wisdom": 1,
                "men": 8,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_aoe"],
        },
        # --- 2. Опытные бойцы (Veterans) [Tier 0-4] ---
        "tunnel_rat": {
            "id": "tunnel_rat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A rat with large claws for digging. Moves silently in the dark.",
            "extra_tags": ["stealth", "digger"],
            "base_stats": {
                "strength": 5,
                "agility": 12,
                "endurance": 6,
                "intelligence": 2,
                "wisdom": 3,
                "men": 5,
                "perception": 12,
                "charisma": 1,
                "luck": 6,
            },
            "fixed_loadout": {},
            "skills": ["stealth", "attack_heavy"],
        },
        "pack_rat": {
            "id": "pack_rat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A rat that never fights alone. Always looks for allies.",
            "extra_tags": ["pack_tactics", "social"],
            "base_stats": {
                "strength": 7,
                "agility": 10,
                "endurance": 8,
                "intelligence": 3,
                "wisdom": 2,
                "men": 6,
                "perception": 10,
                "charisma": 4,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage"],
        },
        "screecher": {
            "id": "screecher",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A rat with an oversized throat pouch. Emits ear-piercing shrieks.",
            "extra_tags": ["support", "alarm"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 6,
                "intelligence": 4,
                "wisdom": 3,
                "men": 5,
                "perception": 14,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "summon_minion"],
        },
        # --- 3. Элита (Elites) [Tier 2-5] ---
        "plague_rat": {
            "id": "plague_rat",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A rat covered in weeping sores and green pustules. Leaves a trail of sickness.",
            "extra_tags": ["plague", "poison", "aura"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 12,
                "intelligence": 3,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 1,
                "luck": 2,
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_poison"],
        },
        "rotfang": {
            "id": "rotfang",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A large rat with dripping, rotten fangs. Its bite causes necrosis.",
            "extra_tags": ["necrosis", "bleed"],
            "base_stats": {
                "strength": 12,
                "agility": 12,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 4,
                "men": 10,
                "perception": 12,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_bleed"],
        },
        "blight_carrier": {
            "id": "blight_carrier",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A bloated rat that explodes upon death, spreading disease.",
            "extra_tags": ["explosive", "blight"],
            "base_stats": {
                "strength": 10,
                "agility": 6,
                "endurance": 16,
                "intelligence": 2,
                "wisdom": 2,
                "men": 12,
                "perception": 8,
                "charisma": 1,
                "luck": 1,
            },
            "fixed_loadout": {},
            "skills": ["explode_on_death", "debuff_poison"],
        },
        # --- 4. Боссы (Bosses) [Tier 3-7] ---
        "rat_brute": {
            "id": "rat_brute",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A hulking, muscular rat, possibly mutated. Smashes through obstacles.",
            "extra_tags": ["brute", "mutated", "strong"],
            "base_stats": {
                "strength": 18,
                "agility": 8,
                "endurance": 20,
                "intelligence": 4,
                "wisdom": 4,
                "men": 15,
                "perception": 10,
                "charisma": 5,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "buff_rage", "attack_ranged"],
        },
        "brood_alpha": {
            "id": "brood_alpha",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A cunning alpha rat that directs the swarm with chirps and gestures.",
            "extra_tags": ["leader", "alpha", "tactician"],
            "base_stats": {
                "strength": 14,
                "agility": 16,
                "endurance": 14,
                "intelligence": 10,
                "wisdom": 8,
                "men": 12,
                "perception": 16,
                "charisma": 10,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_fast", "attack_heavy"],
        },
        "rat_king": {
            "id": "rat_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A horrific amalgamation of several rats joined at the tail. Moves as one entity.",
            "extra_tags": ["king", "abomination", "hive_mind"],
            "base_stats": {
                "strength": 16,
                "agility": 10,
                "endurance": 25,
                "intelligence": 14,
                "wisdom": 12,
                "men": 20,
                "perception": 18,
                "charisma": 15,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_poison", "attack_fast", "summon_minion"],
        },
    },
}
