"""
СЕМЕЙСТВО: ЗМЕИ (Засада, укус, отступление)
===========================================
Логика: засада -> укус -> отступление
"""

from ..monster_structs import MonsterFamily

SNAKES_FAMILY: MonsterFamily = {
    "id": "snake_den",
    "archetype": "beast",
    "organization_type": "solitary",
    "default_tags": ["beast", "snake", "venomous", "ambush"],
    "hierarchy": {
        "minions": ["nestling", "hatchling"],
        "veterans": ["coil_striker", "brush_serpent", "venom_fang", "neuro_viper"],
        "elites": ["constrictor", "serpent_alpha"],
        "boss": ["basilisk", "world_serpent"],
    },
    "variants": {
        # --- 1. Молодь / Фон (Minions) ---
        "nestling": {
            "id": "nestling",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A tiny snake, barely out of the egg. Hisses defensively.",
            "extra_tags": ["young", "weak"],
            "base_stats": {
                "strength": 2,
                "agility": 8,
                "endurance": 3,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 6,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "hatchling": {
            "id": "hatchling",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A young, fast snake. Slithers away at the first sign of danger.",
            "extra_tags": ["young", "fast"],
            "base_stats": {
                "strength": 3,
                "agility": 12,
                "endurance": 4,
                "intelligence": 1,
                "wisdom": 1,
                "men": 5,
                "perception": 8,
                "charisma": 1,
                "luck": 6,
            },
            "fixed_loadout": {},
            "skills": ["attack_fast"],
        },
        # --- 2. Охотники (Veterans) ---
        "coil_striker": {
            "id": "coil_striker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A muscular snake coiled like a spring. Ready to launch itself.",
            "extra_tags": ["striker", "fast"],
            "base_stats": {
                "strength": 8,
                "agility": 14,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 2,
                "men": 6,
                "perception": 10,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "attack_basic"],
        },
        "brush_serpent": {
            "id": "brush_serpent",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A snake with scales that perfectly match the surrounding foliage.",
            "extra_tags": ["stealth", "ambusher"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 7,
                "intelligence": 3,
                "wisdom": 3,
                "men": 6,
                "perception": 12,
                "charisma": 1,
                "luck": 8,
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "attack_heavy"],
        },
        "venom_fang": {
            "id": "venom_fang",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A brightly colored snake with dripping fangs. Hisses a warning.",
            "extra_tags": ["poison", "ranged"],
            "base_stats": {
                "strength": 5,
                "agility": 10,
                "endurance": 6,
                "intelligence": 2,
                "wisdom": 2,
                "men": 8,
                "perception": 10,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_poison"],
        },
        "neuro_viper": {
            "id": "neuro_viper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A sleek, dark viper. Its venom attacks the nervous system.",
            "extra_tags": ["poison", "control"],
            "base_stats": {
                "strength": 4,
                "agility": 14,
                "endurance": 5,
                "intelligence": 3,
                "wisdom": 3,
                "men": 10,
                "perception": 12,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_slow"],
        },
        # --- 3. Доминирующие (Elites) ---
        "constrictor": {
            "id": "constrictor",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A massive, thick-bodied snake capable of crushing bones.",
            "extra_tags": ["brute", "grappler"],
            "base_stats": {
                "strength": 16,
                "agility": 6,
                "endurance": 18,
                "intelligence": 2,
                "wisdom": 2,
                "men": 10,
                "perception": 8,
                "charisma": 1,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_stun", "debuff_bleed"],
        },
        "serpent_alpha": {
            "id": "serpent_alpha",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A large, scarred snake that seems to command others nearby.",
            "extra_tags": ["leader", "alpha"],
            "base_stats": {
                "strength": 12,
                "agility": 12,
                "endurance": 14,
                "intelligence": 5,
                "wisdom": 5,
                "men": 12,
                "perception": 14,
                "charisma": 8,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_fast", "debuff_weaken"],
        },
        # --- 4. Боссы (Bosses) ---
        "basilisk": {
            "id": "basilisk",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A legendary serpent with a gaze that turns flesh to stone.",
            "extra_tags": ["legendary", "petrify"],
            "base_stats": {
                "strength": 20,
                "agility": 10,
                "endurance": 25,
                "intelligence": 8,
                "wisdom": 10,
                "men": 20,
                "perception": 18,
                "charisma": 10,
                "luck": 5,
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_poison", "attack_aoe"],
        },
        "world_serpent": {
            "id": "world_serpent",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "An ancient, colossal snake that seems to be part of the earth itself.",
            "extra_tags": ["ancient", "colossal"],
            "base_stats": {
                "strength": 30,
                "agility": 5,
                "endurance": 40,
                "intelligence": 15,
                "wisdom": 20,
                "men": 30,
                "perception": 20,
                "charisma": 15,
                "luck": 10,
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_execute", "debuff_poison"],
        },
    },
}
