from ..monster_structs import MonsterFamily

WEREWOLVES_FAMILY: MonsterFamily = {
    "id": "werewolf_pack",
    "archetype": "humanoid",
    "organization_type": "pack",
    "default_tags": ["beast", "lycanthrope", "predator", "night", "fur"],
    "hierarchy": {
        "minions": ["ww_whelp", "ww_scavenger", "ww_lurker"],
        "veterans": ["ww_pack_hunter", "ww_stalker", "ww_prowler"],
        "elites": ["ww_enforcer", "ww_bloodfang", "ww_howler"],
        "boss": ["ww_alpha", "ww_elder_alpha", "ww_moon_tyrant"],
    },
    "variants": {
        # === 1. Низ стаи (Minions) ===
        "ww_whelp": {
            "id": "ww_whelp",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "Young werewolf, patchy fur, thin limbs, inexperienced but aggressive.",
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 6,
                "intelligence": 3,
                "wisdom": 2,
                "men": 4,
                "perception": 8,
                "charisma": 1,
                "luck": 3,
            },
            "fixed_loadout": {"main_hand": "claw_weak", "chest_garment": "rags_dirty"},
            "skills": ["clumsy_bite", "growl"],
        },
        "ww_scavenger": {
            "id": "ww_scavenger",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "Hunched, mange-ridden, sniffing the ground, cowardly.",
            "base_stats": {
                "strength": 7,
                "agility": 8,
                "endurance": 8,
                "intelligence": 4,
                "wisdom": 3,
                "men": 5,
                "perception": 12,
                "charisma": 1,
                "luck": 6,
            },
            "fixed_loadout": {"main_hand": "claw_dirty", "legs_garment": "pants_torn"},
            "skills": ["scavenge_bite", "flee"],
        },
        "ww_lurker": {
            "id": "ww_lurker",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "Dark fur, moves silently in shadows, glowing yellow eyes.",
            "base_stats": {
                "strength": 9,
                "agility": 14,
                "endurance": 7,
                "intelligence": 5,
                "wisdom": 3,
                "men": 6,
                "perception": 10,
                "charisma": 2,
                "luck": 4,
            },
            "fixed_loadout": {"main_hand": "claw_shadow", "outer_garment": "cloak_shredded"},
            "skills": ["ambush", "shadow_step"],
        },
        # === 2. Охотники (Veterans) ===
        "ww_pack_hunter": {
            "id": "ww_pack_hunter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "Standard pack warrior, disciplined, coordinates attacks.",
            "base_stats": {
                "strength": 12,
                "agility": 12,
                "endurance": 10,
                "intelligence": 5,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 4,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "fang_wolf", "off_hand": "claw_wolf", "legs_garment": "leather_breeches"},
            "skills": ["coordinated_strike", "flank"],
        },
        "ww_stalker": {
            "id": "ww_stalker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "Lean, muscular, obsessed with the target, relentless.",
            "base_stats": {
                "strength": 11,
                "agility": 16,
                "endurance": 12,
                "intelligence": 6,
                "wisdom": 5,
                "men": 10,
                "perception": 16,
                "charisma": 3,
                "luck": 5,
            },
            "fixed_loadout": {
                "main_hand": "claw_razor",
                "chest_armor": "leather_harness",
                "feet_armor": "padded_wraps",
            },
            "skills": ["tracking", "rend", "pounce"],
        },
        "ww_prowler": {
            "id": "ww_prowler",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "Fast killer, gray fur, bloodstained claws.",
            "base_stats": {
                "strength": 10,
                "agility": 20,
                "endurance": 10,
                "intelligence": 7,
                "wisdom": 4,
                "men": 12,
                "perception": 14,
                "charisma": 3,
                "luck": 8,
            },
            "fixed_loadout": {"main_hand": "claw_assassin", "off_hand": "claw_assassin", "amulet": "tooth_necklace"},
            "skills": ["throat_bite", "dash", "bleed_attack"],
        },
        # === 3. Альфы (Elites) ===
        "ww_enforcer": {
            "id": "ww_enforcer",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "Huge, bulky muscle, scarred snout, brutal strength.",
            "base_stats": {
                "strength": 22,
                "agility": 8,
                "endurance": 18,
                "intelligence": 4,
                "wisdom": 3,
                "men": 10,
                "perception": 8,
                "charisma": 6,
                "luck": 2,
            },
            "fixed_loadout": {
                "main_hand": "fist_heavy",
                "chest_armor": "chain_scraps",
                "legs_armor": "plate_greaves_broken",
            },
            "skills": ["slam", "intimidate", "bone_breaker"],
        },
        "ww_bloodfang": {
            "id": "ww_bloodfang",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "Red-tinted fur, frenzy, constantly dripping saliva.",
            "base_stats": {
                "strength": 18,
                "agility": 14,
                "endurance": 14,
                "intelligence": 3,
                "wisdom": 2,
                "men": 15,
                "perception": 10,
                "charisma": 4,
                "luck": 6,
            },
            "fixed_loadout": {
                "main_hand": "fang_vampiric",
                "off_hand": "claw_serrated",
                "chest_garment": "war_paint_blood",
            },
            "skills": ["blood_frenzy", "lifesteal_bite", "howl_rage"],
        },
        "ww_howler": {
            "id": "ww_howler",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "Silver streaks in fur, head thrown back, mystical aura.",
            "base_stats": {
                "strength": 12,
                "agility": 10,
                "endurance": 12,
                "intelligence": 10,
                "wisdom": 14,
                "men": 25,
                "perception": 12,
                "charisma": 16,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "totem_wolf_paw", "chest_armor": "robe_shredded", "amulet": "moon_stone"},
            "skills": ["terror_howl", "pack_buff_haste", "summon_whelps"],
        },
        # === 4. Вожаки (Bosses) ===
        "ww_alpha": {
            "id": "ww_alpha",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "Dominant posture, prime physical condition, intelligent eyes.",
            "base_stats": {
                "strength": 25,
                "agility": 18,
                "endurance": 25,
                "intelligence": 12,
                "wisdom": 10,
                "men": 20,
                "perception": 18,
                "charisma": 20,
                "luck": 10,
            },
            "fixed_loadout": {
                "main_hand": "claw_alpha",
                "off_hand": "fang_alpha",
                "chest_armor": "breastplate_leather_masterwork",
                "legs_armor": "pants_noble_shredded",
                "ring_1": "ring_pack_leader",
            },
            "skills": ["alpha_command", "takedown", "execute"],
        },
        "ww_elder_alpha": {
            "id": "ww_elder_alpha",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "White fur, battle scars, slower but hits like a truck, wise.",
            "base_stats": {
                "strength": 30,
                "agility": 10,
                "endurance": 35,
                "intelligence": 18,
                "wisdom": 20,
                "men": 30,
                "perception": 20,
                "charisma": 25,
                "luck": 15,
            },
            "fixed_loadout": {
                "main_hand": "claw_ancient",
                "chest_armor": "armor_ancient_hero",
                "amulet": "amulet_ancestors",
            },
            "skills": ["ancestral_howl", "ignore_pain", "crush"],
        },
        "ww_moon_tyrant": {
            "id": "ww_moon_tyrant",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "Massive size, glowing moonlight eyes, radiates cosmic horror.",
            "base_stats": {
                "strength": 35,
                "agility": 25,
                "endurance": 50,
                "intelligence": 25,
                "wisdom": 30,
                "men": 100,
                "perception": 30,
                "charisma": 30,
                "luck": 50,
            },
            "fixed_loadout": {
                "main_hand": "claw_moon_infused",
                "off_hand": "claw_void",
                "chest_garment": "aura_moonlight",
            },
            "skills": ["lunar_beam", "gravity_crush", "mass_hysteria"],
        },
    },
}
